name: Selenium CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Chrome
      run: |
        sudo apt-get update
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Chromedriver
      run: |
        sudo apt-get install -y curl unzip
        # Obtener la versión de Chrome
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        # Obtener la versión de Chromedriver compatible
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        echo "Instalando Chromedriver versión: $CHROMEDRIVER_VERSION"
        # Descargar Chromedriver
        wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Verify Chrome and Chromedriver versions
      run: |
        google-chrome --version
        chromedriver --version

    - name: Install Dependencies
      run: npm install

    - name: Run Selenium Test
      run: node test.js
