name: Selenium CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Chrome
      run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

    - name: Install Chromedriver
      run: |
        sudo apt-get install -y unzip
        wget -N https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver


    - name: Install Dependencies
      run: npm install

    - name: Install Chrome
      run: sudo apt-get install -y chromium-browser

    - name: Run Selenium Test
      run: node test.js
