name: Selenium CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Chrome
      run: |
        sudo apt-get update && sudo apt-get install -y google-chrome-stable

    - name: Install Chromedriver
      run: |
        sudo apt-get install -y unzip
        wget -N https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        sudo unzip chromedriver_linux64.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    # Este es el nuevo paso para verificar las versiones instaladas
    - name: Verify Chrome and Chromedriver versions
      run: |
        google-chrome --version
        chromedriver --version

    - name: Install Dependencies
      run: npm install

    - name: Run Selenium Test
      run: node test.js
